const GUI_ITEMS = [
  {
    label: 'Canvas Size',
    key: 'canvasSize',
    type: 'select',
    options: ['256', '400', '512', '800', '1024', '1600', '2048', '640x480', '1280x720', '1920x1080', '3840x2160', '7680x4320'],
  },
  {
    label: 'Weight Combination',
    key: 'weightCombination',
    type: 'select',
    options: ['sum', 'average', 'power', 'min', 'max'],
  },
  {
    label: 'WC: power Exponent',
    key: 'weightPower',
    step: 0.01,
    type: 'float',
    min: -10,
    max: 10,
  },
  {
    label: 'Square Weights?',
    key: 'weightSquare',
    type: 'bool',
  },
  {
    label: 'Along vs Around',
    key: 'sampleMethod',
    type: 'float',
    step: 0.01,
    min: 0,
    max: 1,
  },
  {
    label: 'Funktions',
    key: 'rbfType',
    type: 'select',
    options: [
      'gaussian',
      'cauchy',
      'wave',
      'wave2',
      'multiquadric',
      'inverse-multiquadric',
      'inverse-quadratic',
      'expSinusoidal',
      'cubicPulse',
      'dampedCosine',
      'sinc',
      'thinPlateSpline',
      //'logarithmic',
      'spline',
      //'polynomial',
      //'exponential',
      //'rationalQuadratic',
      'bump',
      'linear',
      'cubic',
      'quintic',
      //'thinPlate',
    ],
  },
  {
    label: 'Spread',
    key: 'spread',
    step: 0.01,
    type: 'float',
    min: 0,
    max: 16,
  },
  {
    label: 'Number of Slices',
    key: 'n',
    step: .01,
    type: 'float',
    min: 0,
    max: 37,
  },
  {
    label: 'Zoom Out',
    key: 'zoom',
    step: 1,
    type: 'float',
    min: 1,
    max: 300,
  },
  {
    label: 'Slices Counted',
    key: 'iterations',
    step: 1,
    type: 'float',
    min: 1,
    max: 36,
  },
  {
    label: 'Wrap',
    key: 'outsideHandling',
    type: 'select',
    options: ['mirror', 'repeat', 'clamp'],
  },
  {
    label: 'Blend Pixels?',
    key: 'bilinearInterpolation',
    type: 'bool',
  },
  {
    label: 'Spiral Turn',
    key: 'spiralTurn',
    step: 0.1,
    type: 'float',
    min: -3,
    max: 3,
  },
  {
    label: 'Spiral Size',
    key: 'spiralWidth',
    step: 0.1,
    type: 'float',
    min: 0.1,
    max: 5,
  },
  {
    label: 'Supersampling',
    key: 'supersampling',
    type: 'select',
    options: ['1', '2', '4', '8', '16'],
  },
  {
    label: 'Input Scale',
    key: 'inputScale',
    step: 0.01,
    type: 'float',
    min: 0.01,
    max: 10,
  },
  {
    label: 'Input X Offset',
    key: 'inputXOffset',
    step: 0.1,
    type: 'float',
    min: -360,
    max: 360,
  },
  {
    label: 'Input Y Offset',
    key: 'inputYOffset',
    step: 0.1,
    type: 'float',
    min: -360,
    max: 360,
  },
  {
    label: 'Output X Offset',
    key: 'outputXOffset',
    step: 0.01,
    type: 'float',
    min: -10,
    max: 10,
  },
  {
    label: 'Output Y Offset',
    key: 'outputYOffset',
    step: 0.01,
    type: 'float',
    min: -10,
    max: 10,
  },
  {
    label: 'Rotation',
    key: 'rotation',
    step: 0.001,
    type: 'float',
    min: -360,
    max: 360,
  },
  {
    label: 'Hue Rotation',
    key: 'hueRotation',
    step: 0.001,
    type: 'float',
    min: -360.0,
    max: 360.0,
  },
  {
    label: 'Saturation',
    key: 'saturation',
    step: 0.01,
    type: 'float',
    min: 0.0,
    max: 5.0,
  },
  {
    label: 'Value',
    key: 'value',
    step: 0.01,
    type: 'float',
    min: 0.0,
    max: 5.0,
  },
  {
    label: 'Bloom',
    key: 'bloom',
    type: 'float',
    step: 0.001,
    min: 0,
    max: 3,
  },
];

export default GUI_ITEMS;
